source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WeiboSDK_Example', :exclusive => true do
  pod "WeiboSDK", :path => "../"
end

target 'WeiboSDK_Tests', :exclusive => true do
  pod "WeiboSDK", :path => "../"

  
end
